change CI test to tt-alchemist

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -353,37 +353,6 @@ jobs:
         ${{ steps.strings.outputs.build-output-dir }}/runtime/test/ttnn/gtest/test_runtime_worker
         ${{ steps.strings.outputs.build-output-dir }}/runtime/test/ttnn/gtest/test_tensor_serialization
 
-
-    - name: Run TTNN-Standalone test
-      shell: bash
-      if: ${{ matrix.build.type == 'ttnn_standalone' && matrix.build.suite == 'run' }}
-      run: |
-        export TT_METAL_HOME="${{ steps.strings.outputs.install-output-dir }}/tt-metal"
-        export TT_METAL_LIB="${{ steps.strings.outputs.install-output-dir }}/lib"
-        export LD_LIBRARY_PATH="${{ steps.strings.outputs.install-output-dir }}/lib:${TTMLIR_TOOLCHAIN_DIR}/lib:${LD_LIBRARY_PATH}"
-        cd ${{ steps.strings.outputs.install-output-dir }}/${{ matrix.build.path }}
-        ./ttnn-standalone
-
-    - name: Run TTNN-Standalone load_input test
-      shell: bash
-      if: ${{ matrix.build.type == 'ttnn_standalone' && matrix.build.suite == 'run' }}
-      run: |
-        source env/activate
-        export LD_LIBRARY_PATH="${{ steps.strings.outputs.install-output-dir }}/lib:${TTMLIR_TOOLCHAIN_DIR}/lib:${LD_LIBRARY_PATH}"
-        export TT_METAL_HOME="${{ steps.strings.outputs.install-output-dir }}/tt-metal"
-        export TT_METAL_LIB="${{ steps.strings.outputs.install-output-dir }}/lib"
-
-        # Process the load_input test
-        cd ${{ steps.strings.outputs.build-output-dir }}/test/ttmlir/EmitC/TTNN/load_input
-        ttmlir-opt -ttir-to-emitc-pipeline="load-input-tensors-from-disk=true" ttnn_load_input_tensors.mlir | ttmlir-translate -mlir-to-cpp -o ttnn-standalone.cpp
-
-        # Copy generated code and tensor files to ttnn-standalone directory
-        cp arg0.tensorbin arg1.tensorbin ttnn-standalone.cpp ${{ steps.strings.outputs.install-output-dir }}/tools/ttnn-standalone/
-
-        # Build and run
-        cd ${{ steps.strings.outputs.install-output-dir }}/tools/ttnn-standalone
-        ./run
-
     - name: Builder Tests
       if: matrix.build.type == 'builder'
       shell: bash
@@ -581,6 +550,19 @@ jobs:
       run: |
         source testenv/bin/activate
         tt-alchemist model-to-python tools/tt-alchemist/test/models/mnist.mlir
+
+    - name: Run tt-alchemist API test - generate-cpp (load tensors)
+      shell: bash
+      run: |
+        source testenv/bin/activate
+        OUTPUT_DIR=/tmp/test-load-tensors
+        rm -rf $OUTPUT_DIR
+        tt-alchemist generate-cpp --pipeline-options 'load-input-tensors-from-disk=true' test/ttmlir/EmitC/TTNN/load_input/ttnn_load_input_tensors.mlir --output $OUTPUT_DIR --standalone
+        cp test/ttmlir/EmitC/TTNN/load_input/dump_inputs.py $OUTPUT_DIR
+        cd $OUTPUT_DIR
+        [ -d $OUTPUT_DIR ] || { echo "Directory not found: $OUTPUT_DIR" >&2; exit 1; }
+        python dump_inputs.py
+        ./run
 
     - name: Run tt-alchemist API test - generate-cpp (mnist)
       shell: bash
