Create ttrt query repro

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -39,142 +39,142 @@ jobs:
           echo "DOCKER_CI_IMAGE $DOCKER_CI_IMAGE"
           echo "docker-image=$DOCKER_CI_IMAGE" >> "$GITHUB_OUTPUT"
 
-  build-ttmlir:
-    needs: build-image
-    timeout-minutes: 120
-    strategy:
-      fail-fast: false
-      matrix:
-        build: [
-          # {runs-on: ubuntu-latest, enable_perf: OFF, name: "run", ttrt_flags: ""},
-          {runs-on: ubuntu-latest, enable_perf: ON, name: "perf", ttrt_flags: ""},
-        ]
+  # build-ttmlir:
+  #   needs: build-image
+  #   timeout-minutes: 120
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build: [
+  #         # {runs-on: ubuntu-latest, enable_perf: OFF, name: "run", ttrt_flags: ""},
+  #         {runs-on: ubuntu-latest, enable_perf: ON, name: "perf", ttrt_flags: ""},
+  #       ]
 
-    name: Build tt-mlir
-    runs-on: ${{ matrix.build.runs-on }}
+  #   name: Build tt-mlir
+  #   runs-on: ${{ matrix.build.runs-on }}
 
-    container:
-      image: ${{ needs.build-image.outputs.docker-image }}
+  #   container:
+  #     image: ${{ needs.build-image.outputs.docker-image }}
 
-    steps:
+  #   steps:
 
-    - uses: actions/checkout@v4
-      with:
-          fetch-depth: 0
+  #   - uses: actions/checkout@v4
+  #     with:
+  #         fetch-depth: 0
 
-    - name: Set reusable strings
-      id: strings
-      shell: bash
-      run: |
-        echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
-        echo "build-output-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"
-        echo "install-output-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
+  #   - name: Set reusable strings
+  #     id: strings
+  #     shell: bash
+  #     run: |
+  #       echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
+  #       echo "build-output-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"
+  #       echo "install-output-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
 
-    - name: Git safe dir
-      run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}
+  #   - name: Git safe dir
+  #     run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}
 
-    - name: ccache
-      uses: hendrikmuhs/ccache-action@v1.2
-      with:
-        create-symlink: true
-        key: ${{ matrix.build.runs-on }}-run-ON-perf-${{ matrix.build.enable_perf }}-${{ env.SDK_VERSION }}
+  #   - name: ccache
+  #     uses: hendrikmuhs/ccache-action@v1.2
+  #     with:
+  #       create-symlink: true
+  #       key: ${{ matrix.build.runs-on }}-run-ON-perf-${{ matrix.build.enable_perf }}-${{ env.SDK_VERSION }}
 
-    # Build project
+  #   # Build project
 
-    - name: Configure CMake
-      shell: bash
-      run: |
-        source env/activate
-        cmake -G Ninja \
-        -B ${{ steps.strings.outputs.build-output-dir }} \
-        -DCMAKE_CXX_COMPILER=clang++-17 \
-        -DCMAKE_C_COMPILER=clang-17 \
-        -DCMAKE_BUILD_TYPE=Release \
-        -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.install-output-dir }} \
-        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-        -DTTMLIR_ENABLE_RUNTIME=ON \
-        -DTTMLIR_ENABLE_RUNTIME_TESTS=ON \
-        -DTT_RUNTIME_ENABLE_PERF_TRACE=${{ matrix.build.enable_perf }} \
-        -DTTMLIR_ENABLE_STABLEHLO=ON \
-        -S ${{ steps.strings.outputs.work-dir }}
+  #   - name: Configure CMake
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       cmake -G Ninja \
+  #       -B ${{ steps.strings.outputs.build-output-dir }} \
+  #       -DCMAKE_CXX_COMPILER=clang++-17 \
+  #       -DCMAKE_C_COMPILER=clang-17 \
+  #       -DCMAKE_BUILD_TYPE=Release \
+  #       -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.install-output-dir }} \
+  #       -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
+  #       -DTTMLIR_ENABLE_RUNTIME=ON \
+  #       -DTTMLIR_ENABLE_RUNTIME_TESTS=ON \
+  #       -DTT_RUNTIME_ENABLE_PERF_TRACE=${{ matrix.build.enable_perf }} \
+  #       -DTTMLIR_ENABLE_STABLEHLO=ON \
+  #       -S ${{ steps.strings.outputs.work-dir }}
 
-    - name: Build
-      shell: bash
-      run: |
-        source env/activate
-        cmake --build ${{ steps.strings.outputs.build-output-dir }}
-        cmake --install ${{ steps.strings.outputs.build-output-dir }} --component Test
+  #   - name: Build
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       cmake --build ${{ steps.strings.outputs.build-output-dir }}
+  #       cmake --install ${{ steps.strings.outputs.build-output-dir }} --component Test
 
-    # - name: Lint
-    #   shell: bash
-    #   if: matrix.build.enable_perf == 'OFF'
-    #   run: |
-    #     source env/activate
-    #     cmake --build ${{ steps.strings.outputs.build-output-dir }} -- clang-tidy
+  #   # - name: Lint
+  #   #   shell: bash
+  #   #   if: matrix.build.enable_perf == 'OFF'
+  #   #   run: |
+  #   #     source env/activate
+  #   #     cmake --build ${{ steps.strings.outputs.build-output-dir }} -- clang-tidy
 
-    - name: Run Test
-      shell: bash
-      run: |
-        source env/activate
-        cmake --build ${{ steps.strings.outputs.build-output-dir }} -- check-ttmlir
+  #   - name: Run Test
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       cmake --build ${{ steps.strings.outputs.build-output-dir }} -- check-ttmlir
 
-    - name: Upload Test Report
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-reports-${{ matrix.build.runs-on }}-perf-${{ matrix.build.enable_perf }}
-        path: build/test/report.xml
+  #   - name: Upload Test Report
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: test-reports-${{ matrix.build.runs-on }}-perf-${{ matrix.build.enable_perf }}
+  #       path: build/test/report.xml
 
-    - name: Show Test Report
-      uses: mikepenz/action-junit-report@v4
-      if: success() || failure()
-      with:
-        report_paths: build/test/report.xml
-        check_name: MLIR Tests
+  #   - name: Show Test Report
+  #     uses: mikepenz/action-junit-report@v4
+  #     if: success() || failure()
+  #     with:
+  #       report_paths: build/test/report.xml
+  #       check_name: MLIR Tests
 
-    # Build and upload ttrt
+  #   # Build and upload ttrt
 
-    - name: Build ttrt
-      shell: bash
-      run: |
-        source env/activate
-        cmake --build ${{ steps.strings.outputs.build-output-dir }} -- ttrt
+  #   - name: Build ttrt
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       cmake --build ${{ steps.strings.outputs.build-output-dir }} -- ttrt
 
-    - name: Test ttrt
-      shell: bash
-      run: |
-        source env/activate
-        TTRT_LOGGER_LEVEL=DEBUG; ttrt query --save-artifacts
+  #   - name: Test ttrt
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       TTRT_LOGGER_LEVEL=DEBUG; ttrt query --save-artifacts
 
-    - name: Upload ttrt whl
-      uses: actions/upload-artifact@v4
-      with:
-        name: ttrt-whl-${{ matrix.build.name }}
-        path: build/runtime/tools/python/build/ttrt*.whl
+  #   - name: Upload ttrt whl
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: ttrt-whl-${{ matrix.build.name }}
+  #       path: build/runtime/tools/python/build/ttrt*.whl
 
-    # This is needed to preserve file permissions
-    # https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
-    - name: 'Tar install directory'
-      shell: bash
-      working-directory: ${{ steps.strings.outputs.install-output-dir }}
-      run: tar cvf artifact.tar .
+  #   # This is needed to preserve file permissions
+  #   # https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
+  #   - name: 'Tar install directory'
+  #     shell: bash
+  #     working-directory: ${{ steps.strings.outputs.install-output-dir }}
+  #     run: tar cvf artifact.tar .
 
-    - name: Upload install folder to archive
-      uses: actions/upload-artifact@v4
-      with:
-        name: install-artifacts-${{ matrix.build.name }}
-        path: ${{ steps.strings.outputs.install-output-dir }}/artifact.tar
+  #   - name: Upload install folder to archive
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: install-artifacts-${{ matrix.build.name }}
+  #       path: ${{ steps.strings.outputs.install-output-dir }}/artifact.tar
 
-    - name: Get the latest tag
-      shell: bash
-      run: |
-        latest_tag=$(git describe --tags --abbrev=0)
-        latest_tag=${latest_tag#v}
-        echo "latest_tag=$latest_tag" >> $GITHUB_ENV
-        commit_count=$(git rev-list ${{ env.latest_tag }}..HEAD --count)
-        echo "commit_count=$commit_count" >> $GITHUB_ENV
-        version="${{ env.latest_tag }}.${{ env.commit_count }}"
-        echo "version=$version" >> $GITHUB_ENV
-        echo $version
+  #   - name: Get the latest tag
+  #     shell: bash
+  #     run: |
+  #       latest_tag=$(git describe --tags --abbrev=0)
+  #       latest_tag=${latest_tag#v}
+  #       echo "latest_tag=$latest_tag" >> $GITHUB_ENV
+  #       commit_count=$(git rev-list ${{ env.latest_tag }}..HEAD --count)
+  #       echo "commit_count=$commit_count" >> $GITHUB_ENV
+  #       version="${{ env.latest_tag }}.${{ env.commit_count }}"
+  #       echo "version=$version" >> $GITHUB_ENV
+  #       echo $version
 
 
   # # Run tests on TT hardware
@@ -417,7 +417,81 @@ jobs:
   #       source env/activate
   #       pytest -ssv runtime/tools/python/test/test_perf.py
 
-  build-and-test-explorer:
+  # build-and-test-explorer:
+  #   needs: build-image
+  #   timeout-minutes: 60
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build: [
+  #         {runs-on: n150, enable_perf: ON, name: "perf"},
+  #       ]
+
+  #   name: Build and test tt-explorer
+  #   runs-on:
+  #     - in-service
+  #     - ${{ matrix.build.runs-on }}
+
+  #   container:
+  #     image: ${{ needs.build-image.outputs.docker-image }}
+
+  #   steps:
+
+  #   - uses: actions/checkout@v4
+  #     with:
+  #         fetch-depth: 0
+
+  #   - name: Set reusable strings
+  #     id: strings
+  #     shell: bash
+  #     run: |
+  #       echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
+  #       echo "build-output-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"
+
+  #   - name: Git safe dir
+  #     run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}
+
+  #   - name: ccache
+  #     uses: hendrikmuhs/ccache-action@v1.2
+  #     with:
+  #       create-symlink: true
+  #       key: ${{ matrix.build.runs-on }}-run-ON-perf-${{ matrix.build.enable_perf }}-${{ env.SDK_VERSION }}
+
+  #   - name: Configure CMake
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       cmake -G Ninja \
+  #       -B ${{ steps.strings.outputs.build-output-dir }} \
+  #       -DCMAKE_CXX_COMPILER=clang++-17 \
+  #       -DCMAKE_C_COMPILER=clang-17 \
+  #       -DCMAKE_BUILD_TYPE=Release \
+  #       -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
+  #       -DTTMLIR_ENABLE_RUNTIME=ON \
+  #       -DTTMLIR_ENABLE_RUNTIME_TESTS=OFF \
+  #       -DTT_RUNTIME_ENABLE_PERF_TRACE=${{ matrix.build.enable_perf }} \
+  #       -DTTMLIR_ENABLE_STABLEHLO=OFF \
+  #       -S ${{ steps.strings.outputs.work-dir }}
+
+  #   - name: Build tt-explorer
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       cmake --build ${{ steps.strings.outputs.build-output-dir }} -- explorer
+
+  #   - name: Test ttrt
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       TTRT_LOGGER_LEVEL=DEBUG; ttrt query --save-artifacts
+
+  #   - name: Run tt-explorer tests
+  #     shell: bash
+  #     run: |
+  #       source env/activate
+  #       pytest tools/explorer/test/run_tests.py
+
+  ttrt-query-repro:
     needs: build-image
     timeout-minutes: 60
     strategy:
@@ -473,20 +547,14 @@ jobs:
         -DTTMLIR_ENABLE_STABLEHLO=OFF \
         -S ${{ steps.strings.outputs.work-dir }}
 
-    - name: Build tt-explorer
+    - name: Build ttrt
       shell: bash
       run: |
         source env/activate
-        cmake --build ${{ steps.strings.outputs.build-output-dir }} -- explorer
+        cmake --build ${{ steps.strings.outputs.build-output-dir }} -- ttrt
 
     - name: Test ttrt
       shell: bash
       run: |
         source env/activate
         TTRT_LOGGER_LEVEL=DEBUG; ttrt query --save-artifacts
-
-    - name: Run tt-explorer tests
-      shell: bash
-      run: |
-        source env/activate
-        pytest tools/explorer/test/run_tests.py
