Initial version of tt-alchemist - cpp paths only
initial structure, bloated

very wip

ttir->emitc works

add env var, clear logs

simplify

csrc

setup.py -> pyproject.toml

cli => cli + api

forgot to add api.py; update envs; rebuild on py filechanges

add conversion to cpp

update a comment

rename wheel target to tt-alchemist

add create-solution api

actually dump cpp code to cpp standalone

Fix ttcore namespace after rebase

Remove TT_ALCHEMIST_LIB_DIR env var

create_solution => generate

Add test

Update metal deps

Build tt-alchemist during build; include deps in whl

Install tt-alchemist wheel before trying to use in CI

Update workarounds.hpp

CI fixes and debug logs

Disable other tests to avoid overusing resources

Fix whl name

Actually download the wheel before trying to install it

Package the .so with the wheel

Add libtt_metal.so

Fix wheel + CI test both APIs

Decouple CI from run-tests; add CI debug logs

Change python -> python3

Make tests run in bash instead of sh

remove debug prints

Update CODEOWNERS

Undo commented out CI jobs; some smaller fixes and comment removals

Refactor TTAlchemist class and external C API

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -444,6 +444,108 @@ jobs:
         check_name: ${{ matrix.build.type }} ${{ matrix.build.runs-on }} ${{ matrix.build.image }} ${{ matrix.build.suite }} Tests
 
 
+  # Dedicated job for tt-alchemist tests
+  test-tt-alchemist:
+    timeout-minutes: 45
+    needs:
+      - build-image
+      - build-ttmlir
+    if: ${{ !failure() && !cancelled() }}
+    runs-on: n150
+    container:
+      image: ${{ needs.build-image.outputs.docker-image }}
+      options: '--device /dev/tenstorrent'
+      volumes:
+        - /dev/hugepages:/dev/hugepages
+        - /dev/hugepages-1G:/dev/hugepages-1G
+        - /etc/udev/rules.d:/etc/udev/rules.d
+        - /lib/modules:/lib/modules
+        - /opt/tt_metal_infra/provisioning/provisioning_env:/opt/tt_metal_infra/provisioning/provisioning_env
+
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+
+    - name: Fetch job id
+      id: fetch-job-id
+      uses: tenstorrent/tt-github-actions/.github/actions/job_id@main
+      with:
+        job_name: "test-tt-alchemist"
+
+    - name: Set reusable strings
+      id: strings
+      shell: bash
+      env:
+        JOB_ID: ${{ steps.fetch-job-id.outputs.job_id }}
+      run: |
+        echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
+        echo "build-output-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"
+        echo "install-output-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
+        echo "test_report_path=report_$JOB_ID.xml" >> "$GITHUB_OUTPUT"
+
+    - name: Git safe dir
+      run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}
+
+    - name: Use install artifacts
+      uses: ./.github/actions/download-artifact
+      with:
+        name: install-artifacts-speedy
+        path: install
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Download Build Artifacts
+      uses: ./.github/actions/download-artifact
+      with:
+        name: build-artifacts-speedy
+        path: build
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Download tt-alchemist wheel
+      uses: actions/download-artifact@v4
+      with:
+        name: tt-alchemist-whl-speedy
+
+    - name: Install tt-alchemist wheel
+      shell: bash
+      run: |
+        python3 -m venv testenv
+        source testenv/bin/activate
+        pip install tt_alchemist-*.whl --force-reinstall
+        echo "Wheel installed successfully"
+
+    - name: Run tt-alchemist API test - model-to-cpp
+      shell: bash
+      run: |
+        source testenv/bin/activate
+        tt-alchemist model-to-cpp tools/tt-alchemist/test/models/mnist.mlir
+
+    - name: Run tt-alchemist API test - generate
+      shell: bash
+      run: |
+        source testenv/bin/activate
+        rm -rf /tmp/test-mlir
+        tt-alchemist generate tools/tt-alchemist/test/models/mnist.mlir /tmp/test-mlir
+        cd /tmp/test-mlir
+        [ -d /tmp/test-mlir ] || { echo "Directory not found: /tmp/test-mlir" >&2; exit 1; }
+        # ./run  # TODO: enable when fixed
+
+    - name: Upload Test Report xml
+      uses: actions/upload-artifact@v4
+      if: success() || failure()
+      with:
+        name: test-reports-tt-alchemist-${{ steps.fetch-job-id.outputs.job_id }}
+        path: ${{ steps.strings.outputs.test_report_path }}
+        if-no-files-found: 'ignore'
+
+    - name: Show Test Report
+      continue-on-error: true
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure()
+      with:
+        report_paths: ${{ steps.strings.outputs.test_report_path }}
+        check_name: tt-alchemist Tests
+
   lint:
     if: github.event_name == 'pull_request'
     needs: build-image
