[EmitC/EmitPy] Load input tensors (#5037)
### Ticket
https://github.com/tenstorrent/tt-mlir/issues/5003

### Problem description
With the addition of `ttnn.load_tensor`, it's now possible to load
tensors from disks. We can use this in EmitC (and EmitPy) pipelines to
load input tensors instead of creating fixed `ttnn.ones`.

### What's changed
Added a pipeline option `load-input-tensors-from-disk` that will
generate a function that will load tensors with `ttnn.load_tensor`.
Currently, it's a boolean option; if specified, it's expected that all
inputs will be loaded and their names are hardcoded to `arg0.tensorbin`,
`arg1.tensorbin`,..., `argN.tensorbin`. These restrictions could be
weakened in the future if there is a necessity (for example, loading
some inputs from defined paths, while generating synthetic tensors for
others).
 
### Checklist
- [x] New/Existing tests provide coverage for changes

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -353,17 +353,6 @@ jobs:
         ${{ steps.strings.outputs.build-output-dir }}/runtime/test/ttnn/gtest/test_runtime_worker
         ${{ steps.strings.outputs.build-output-dir }}/runtime/test/ttnn/gtest/test_tensor_serialization
 
-
-    - name: Run TTNN-Standalone test
-      shell: bash
-      if: ${{ matrix.build.type == 'ttnn_standalone' && matrix.build.suite == 'run' }}
-      run: |
-        export TT_METAL_HOME="${{ steps.strings.outputs.install-output-dir }}/tt-metal"
-        export TT_METAL_LIB="${{ steps.strings.outputs.install-output-dir }}/lib"
-        export LD_LIBRARY_PATH="${{ steps.strings.outputs.install-output-dir }}/lib:${TTMLIR_TOOLCHAIN_DIR}/lib:${LD_LIBRARY_PATH}"
-        cd ${{ steps.strings.outputs.install-output-dir }}/${{ matrix.build.path }}
-        ./ttnn-standalone
-
     - name: Builder Tests
       if: matrix.build.type == 'builder'
       shell: bash
@@ -521,6 +510,7 @@ jobs:
         sparse-checkout: |
           test/ttmlir/models
           tools/tt-alchemist/test
+          test/ttmlir/EmitC/TTNN/load_input
 
     - name: Fetch job id
       id: fetch-job-id
@@ -561,6 +551,18 @@ jobs:
       run: |
         source testenv/bin/activate
         tt-alchemist model-to-python tools/tt-alchemist/test/models/mnist.mlir
+
+    - name: Run tt-alchemist API test - generate-cpp (load tensors)
+      shell: bash
+      run: |
+        source testenv/bin/activate
+        OUTPUT_DIR=/tmp/test-load-tensors
+        rm -rf $OUTPUT_DIR
+        tt-alchemist generate-cpp --pipeline-options 'load-input-tensors-from-disk=true' test/ttmlir/EmitC/TTNN/load_input/ttnn_load_input_tensors.mlir --output $OUTPUT_DIR --standalone
+        cp test/ttmlir/EmitC/TTNN/load_input/arg0.tensorbin test/ttmlir/EmitC/TTNN/load_input/arg1.tensorbin $OUTPUT_DIR
+        cd $OUTPUT_DIR
+        [ -d $OUTPUT_DIR ] || { echo "Directory not found: $OUTPUT_DIR" >&2; exit 1; }
+        ./run
 
     - name: Run tt-alchemist API test - generate-cpp (mnist)
       shell: bash
