add a full install check

diff --git a/.github/workflows/call-build-release.yml b/.github/workflows/call-build-release.yml
--- a/.github/workflows/call-build-release.yml
+++ b/.github/workflows/call-build-release.yml
@@ -133,7 +133,7 @@ jobs:
         source env/activate
         cmake --build ${{ steps.strings.outputs.build-output-dir }} -- compile-ttmlir-tests
 
-    - name: Install
+    - name: Install specific components
       shell: bash
       run: |
         source env/activate
@@ -141,6 +141,14 @@ jobs:
         cmake --install ${{ steps.strings.outputs.build-output-dir }} --component SharedLib
         cmake --install ${{ steps.strings.outputs.build-output-dir }} --component TTNNStandalone
         cmake --install ${{ steps.strings.outputs.build-output-dir }} --component DistributedRuntime
+
+    - name: Install all
+      shell: bash
+      run: |
+        source env/activate
+        rm -rf ${{  steps.strings.outputs.install-output-dir }}
+        cmake --install ${{ steps.strings.outputs.build-output-dir }}
+        test -f "${{ steps.strings.outputs.install-output-dir }}/lib/libTTMLIRCompilerStatic.a" || { echo "ERROR: libTTMLIRCompilerStatic.a not found in ${{ steps.strings.outputs.install-output-dir }}/lib/" && exit 1; }
 
     - name: Build components
       shell: bash
