move install test back to release build since debug build is configured for coverage, so not really appropriate for install and do not want to increase CI times by adding another configuration build

diff --git a/.github/workflows/call-build-release.yml b/.github/workflows/call-build-release.yml
--- a/.github/workflows/call-build-release.yml
+++ b/.github/workflows/call-build-release.yml
@@ -127,6 +127,21 @@ jobs:
         source env/activate
         cmake --build ${{ steps.strings.outputs.build-output-dir }}
 
+    - name: Install (default full install)
+      shell: bash
+      run: |
+        source env/activate
+        rm -rf ${{  steps.strings.outputs.install-output-dir }}
+        cmake --install ${{ steps.strings.outputs.build-output-dir }}
+        test -f "${{ steps.strings.outputs.install-output-dir }}/lib/libTTMLIRCompilerStatic.a" || { echo "ERROR: libTTMLIRCompilerStatic.a not found in ${{ steps.strings.outputs.install-output-dir }}/lib/" && exit 1; }
+
+    - name: Test install
+      shell: bash
+      run: |
+        ${{ steps.strings.outputs.work-dir }}/.github/scripts/bash/test-install.sh \
+          "${{ steps.strings.outputs.install-output-dir }}"
+        rm -rf ${{  steps.strings.outputs.install-output-dir }}
+
     - name: Build tests
       shell: bash
       run: |
