[Draft] test tracy end to end

diff --git a/.github/workflows/schedule-update-durations.yml b/.github/workflows/schedule-update-durations.yml
--- a/.github/workflows/schedule-update-durations.yml
+++ b/.github/workflows/schedule-update-durations.yml
@@ -1,119 +1,174 @@
+# Draft only, testing tracy in CI
 name: Update Test Durations
-
-# This workflow updates (builder) test durations based on the latest push workflow runs.
-# It processes the JUnit XML reports from the last successful push workflows,
-# calculates the test durations, and creates a pull request to update the `.test_durations/{arch}` file.
 
 on:
   workflow_dispatch:
-  schedule:
-    - cron: '0 7 * * 1'
+    inputs:
+      metal_override:
+        description: 'Git SHA of commit in tenstorrent/tt-metal (optional)'
+        required: false
+        type: string
+  # schedule:
+  #   - cron: '0 7 * * 1'
 
 permissions:
-  actions: read
-  contents: write
-  issues: write
+  checks: write
+  packages: write
   pull-requests: write
+  contents: write
+  actions: read
+  issues: write
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
-  update_test_durations:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          fetch-depth: 0
-          # ref: main
-      - uses: actions/setup-python@v6
-        with:
-          python-version: 3.12
-      - name: Process test durations from latest workflows
-        id: get-test-durations
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          repo="${{ github.repository }}"
+  build-image:
+    uses: ./.github/workflows/call-build-docker.yml
+    secrets: inherit
 
-          get_test_results_from_wf() {
-            local wf_name="$1"
-            local conclusions="$2"
-            local num=5
+  prepare-run:
+    uses: ./.github/workflows/call-prepare-run.yml
+    with:
+      builder_build: true
+      build_all: true
+      min_timeout: 180
+    secrets: inherit
 
-            # get json of the last $num workflow runs
-            gh run list --workflow $wf_name -R $repo -b main -L $num --status completed --json attempt,conclusion,databaseId >runs.json
+  release-build:
+    needs: [ prepare-run, build-image ]
+    if: needs.prepare-run.outputs.skip_build != 'true'
+    uses: ./.github/workflows/call-build-release.yml
+    secrets: inherit
+    with:
+      metal_override: ${{ inputs.metal_override }}
+      docker_image: ${{ needs.build-image.outputs.docker-image }}
+      runner: ${{ needs.prepare-run.outputs.runner }}
+      sh_builder: ${{ fromJson(needs.prepare-run.outputs.sh_builder) }}
+      component_matrix: ${{ needs.prepare-run.outputs.build_matrix }}
 
-            counter=0
-            while true; do
-              # Check the status of 'conclusion'
-              conclusion=$(jq -r ".[$counter].conclusion" runs.json)
-
-              if echo "$conclusions" | grep -q -w "$conclusion"; then
-                break
-              else
-                ((++counter))
-
-                # Exit if the counter reaches $num
-                if [ $counter -ge $num ]; then
-                  echo "ERROR: Did not found good workflow within the last $num. Exiting."
-                  exit 1
-                fi
-              fi
-            done
-            curr_wf_id=$(jq -r ".[$counter].databaseId" runs.json)
-            curr_wf_att=$(jq -r ".[$counter].attempt" runs.json)
-            echo "curr_$3_wf_link=https://github.com/$repo/actions/runs/$curr_wf_id/attempts/$curr_wf_att" >> "$GITHUB_OUTPUT"
-            rm -f runs.json
-
-            gh run download $curr_wf_id --pattern "test-reports-*" -R $repo -D ${{runner.temp}}/reports
+  test:
+    needs: [ prepare-run, build-image, release-build ]
+    if: needs.prepare-run.outputs.skip_build != 'true'
+    uses: ./.github/workflows/call-test.yml
+    secrets: inherit
+    with:
+      docker_image: ${{ needs.build-image.outputs.docker-image }}
+      test_matrix: |
+        [
+          {
+            "runs-on": "llmbox",
+            "image": "tracy",
+            "tests": [
+              {
+                "script": "ttnn_runtime.sh",
+                "args": "runtime/test/ttnn/python/distributed/llmbox/test_multiprocess_tracy.py"
+              }
+            ]
           }
+        ]
+      timeout: 60
 
-          # get test results from the last successful push
-          get_test_results_from_wf "on-push.yml" "success" "push"
-
-          python .github/scripts/python/get_test_duration_from_junit_xmls.py ${{runner.temp}}/reports .test_durations
-
-          echo "New test durations:"
-          for file in .test_durations/*; do
-            if [ -f "$file" ]; then
-              echo "" >> $file
-              echo "----- $(basename $file)"
-              cat "$file"
-            fi
-          done
-
-          echo "TODAY=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
-
-      - name: Create Pull Request
-        uses: peter-evans/create-pull-request@v8
-        id: create-pr
-        with:
-          branch: test-durations-update
-          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
-          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
-          base: main
-          commit-message: "Update test durations based on latest workflows ${{ steps.get-test-durations.outputs.TODAY }}"
-          title: "Update test durations based on latest workflows ${{ steps.get-test-durations.outputs.TODAY }}"
-          body: "This PR updates test durations based on latest push (${{ steps.get-test-durations.outputs.curr_push_wf_link }})"
-          labels: tooling
-          delete-branch: true
-          token: ${{ secrets.GH_TOKEN }}
-
-      - name: Enable Pull Request Automerge
-        if: ${{ steps.create-pr.outputs.pull-request-number }}
-        run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
-        env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
-
-      - name: Approve Pull Request
-        if: ${{ steps.create-pr.outputs.pull-request-number }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_APPROVE_TOKEN }}
-        run: |
-          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
-          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
-          gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve
-
-      - name: Generate Summary
-        run: |
-          echo "## Test duration report" >> $GITHUB_STEP_SUMMARY
-          echo "Used [Push](${{ steps.get-test-durations.outputs.curr_push_wf_link }})" >> $GITHUB_STEP_SUMMARY
-          echo "Generated test durations in [Pull Request](${{ steps.create-pr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
+# jobs:
+#   update_test_durations:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v6
+#         with:
+#           fetch-depth: 0
+#           # ref: main
+#       - uses: actions/setup-python@v6
+#         with:
+#           python-version: 3.12
+#       - name: Process test durations from latest workflows
+#         id: get-test-durations
+#         env:
+#           GH_TOKEN: ${{ github.token }}
+#         run: |
+#           repo="${{ github.repository }}"
+#
+#           get_test_results_from_wf() {
+#             local wf_name="$1"
+#             local conclusions="$2"
+#             local num=5
+#
+#             # get json of the last $num workflow runs
+#             gh run list --workflow $wf_name -R $repo -b main -L $num --status completed --json attempt,conclusion,databaseId >runs.json
+#
+#             counter=0
+#             while true; do
+#               # Check the status of 'conclusion'
+#               conclusion=$(jq -r ".[$counter].conclusion" runs.json)
+#
+#               if echo "$conclusions" | grep -q -w "$conclusion"; then
+#                 break
+#               else
+#                 ((++counter))
+#
+#                 # Exit if the counter reaches $num
+#                 if [ $counter -ge $num ]; then
+#                   echo "ERROR: Did not found good workflow within the last $num. Exiting."
+#                   exit 1
+#                 fi
+#               fi
+#             done
+#             curr_wf_id=$(jq -r ".[$counter].databaseId" runs.json)
+#             curr_wf_att=$(jq -r ".[$counter].attempt" runs.json)
+#             echo "curr_$3_wf_link=https://github.com/$repo/actions/runs/$curr_wf_id/attempts/$curr_wf_att" >> "$GITHUB_OUTPUT"
+#             rm -f runs.json
+#
+#             gh run download $curr_wf_id --pattern "test-reports-*" -R $repo -D ${{runner.temp}}/reports
+#           }
+#
+#           # get test results from the last successful push
+#           get_test_results_from_wf "on-push.yml" "success" "push"
+#
+#           python .github/scripts/python/get_test_duration_from_junit_xmls.py ${{runner.temp}}/reports .test_durations
+#
+#           echo "New test durations:"
+#           for file in .test_durations/*; do
+#             if [ -f "$file" ]; then
+#               echo "" >> $file
+#               echo "----- $(basename $file)"
+#               cat "$file"
+#             fi
+#           done
+#
+#           echo "TODAY=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
+#
+#       - name: Create Pull Request
+#         uses: peter-evans/create-pull-request@v8
+#         id: create-pr
+#         with:
+#           branch: test-durations-update
+#           committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
+#           author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
+#           base: main
+#           commit-message: "Update test durations based on latest workflows ${{ steps.get-test-durations.outputs.TODAY }}"
+#           title: "Update test durations based on latest workflows ${{ steps.get-test-durations.outputs.TODAY }}"
+#           body: "This PR updates test durations based on latest push (${{ steps.get-test-durations.outputs.curr_push_wf_link }})"
+#           labels: tooling
+#           delete-branch: true
+#           token: ${{ secrets.GH_TOKEN }}
+#
+#       - name: Enable Pull Request Automerge
+#         if: ${{ steps.create-pr.outputs.pull-request-number }}
+#         run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
+#         env:
+#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
+#
+#       - name: Approve Pull Request
+#         if: ${{ steps.create-pr.outputs.pull-request-number }}
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GH_APPROVE_TOKEN }}
+#         run: |
+#           echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
+#           echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
+#           gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve
+#
+#       - name: Generate Summary
+#         run: |
+#           echo "## Test duration report" >> $GITHUB_STEP_SUMMARY
+#           echo "Used [Push](${{ steps.get-test-durations.outputs.curr_push_wf_link }})" >> $GITHUB_STEP_SUMMARY
+#           echo "Generated test durations in [Pull Request](${{ steps.create-pr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
